### ISSUE TITLE
./merge_dbs.sh error

### ISSUE THREAD

**Issue by 695874419** [Cysu/dgd_person_reid#40]
Traceback (most recent call last):
  File "tools/merge_lists_single_task.py", line 48, in <module>
    main(args)
  File "tools/merge_lists_single_task.py", line 18, in main
    train_files, train_labels = read_kv(osp.join(db_dir, 'train.txt'))
  File "/home/software_mount/wty/dgd_person_reid/tools/../utils/core.py", line 45, in read_kv
    arr = read_list(file_path, coding)
  File "/home/software_mount/wty/dgd_person_reid/tools/../utils/core.py", line 26, in read_list
    with open(file_path, 'r') as f:

IOError: [Errno 2] No such file or directory: 'external/exp/db/train.txt'

**Comment by Cysu** [comment]
@695874419 Did you follow our instructions in https://github.com/Cysu/dgd_person_reid#prepare-data?
